//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Microsoft Power Platform Tools")]
[assembly: AssemblyDescription("Microsoft Power Platform Tools for Visual Studio")]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyProduct("Microsoft Dynamics© CRM")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0000.1")]
[assembly: AssemblyInformationalVersion("0.1.0000.1+g9964c1d")]
[assembly: AssemblyCopyright("© 2021 Microsoft Corporation. All rights reserved")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: Guid("ed6c99c8-7704-45f5-89d5-c2c03393e197")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]